"use client";

import { useQuery } from "@tanstack/react-query";
import { Sparkles } from "lucide-react";

interface Props {
	slug: string;
	cityName: string;
}

export function AISummary({ slug, cityName }: Props) {
	const { data, isLoading } = useQuery<{ summary: string | null }>({
		queryKey: ["city-summary", slug],
		queryFn: async () => {
			const res = await fetch(`/api/cities/${slug}/summary`);
			return res.json() as Promise<{ summary: string | null }>;
		},
		staleTime: 30 * 60 * 1000, // 30 min
		retry: false,
	});

	if (isLoading) {
		return (
			<div className="glass rounded-2xl p-6 animate-pulse">
				<div className="h-4 rounded mb-2" style={{ background: "var(--color-border)", width: "60%" }} />
				<div className="h-4 rounded mb-2" style={{ background: "var(--color-border)", width: "90%" }} />
				<div className="h-4 rounded mb-2" style={{ background: "var(--color-border)", width: "75%" }} />
				<div className="h-4 rounded" style={{ background: "var(--color-border)", width: "50%" }} />
			</div>
		);
	}

	if (!data?.summary) return null;

	return (
		<div className="glass rounded-2xl p-6">
			<div className="flex items-center gap-2 mb-3">
				<Sparkles size={14} style={{ color: "var(--color-accent)" }} />
				<span className="text-xs font-semibold uppercase tracking-widest" style={{ color: "var(--color-muted)" }}>
					AI Overview
				</span>
			</div>
			<p className="text-sm leading-relaxed" style={{ color: "oklch(85% 0 0)" }}>
				{data.summary}
			</p>
			<p className="text-xs mt-3" style={{ color: "var(--color-muted)" }}>
				Generated by Grok AI · {cityName} relocation overview
			</p>
		</div>
	);
}
